name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.12.7
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^2.3.0
  build: ^2.1.0
  build_config: ^1.0.0
  meta: ^1.7.0
  source_gen: ^1.1.0
  freezed_annotation:
    # path: ../freezed_annotation
    git:
      url: https://github.com/long1eu/freezed
      ref: feat/update-deps
      path: packages/freezed_annotation

dev_dependencies:
  json_serializable: ^5.0.1
  json_annotation: ^4.1.0
  build_test: ^2.1.3
  build_runner: ^2.1.2
  test: ^1.17.12
  matcher: ^0.12.11
  source_gen_test: ^1.0.1
